
insert into se_services(se_services) values('Complimentary arrival & departure transfers');
insert into se_services(se_services) values('Reception with concierge assistance');
insert into se_services(se_services) values('Fresh water Swimming pool with sun-loungers');
insert into se_services(se_services) values('Room service');
insert into se_services(se_services) values('Welcome drink upon arrival');
insert into se_services(se_services) values('Daily newspaper with breakfast');
insert into se_services(se_services) values('Laundry & dry cleaning services');
insert into se_services(se_services) values('Private massages, beauty treatments and therapies');
insert into se_services(se_services) values('Manicure, Pedicure and Makeup artist services');
insert into se_services(se_services) values('Private & semi-private sailing tours, cruises and excursions');
insert into se_services(se_services) values('Horse Back Riding');
insert into se_services(se_services) values('Rock Climbing, Hiking & trekking activities');
insert into se_services(se_services) values('All rooms are smoke free');
insert into se_services(se_services) values('Pool bar offering drinks & light snacks');
insert into se_services(se_services) values('Wedding planning & organizing services');
insert into se_services(se_services) values('Fitness');


insert into r_rating(r_rating,r_comment) values(1,'Really bad');
insert into r_rating(r_rating,r_comment) values(2,'It was not as bad');
insert into r_rating(r_rating,r_comment) values(3,'Ok');
insert into r_rating(r_rating,r_comment) values(4,'Good');
insert into r_rating(r_rating,r_comment) values(5,'Very good');

insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values (85, 151, 3, 93.77, 'Malig neo main bronchus');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('8', 153, 3, 746.76, 'Pap smr cytol evid malig');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('4', 151, 2, 415.62, 'Pois-quinoline/hydroxyqu');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('5', 148, 2, 1127.78, 'Open wound jaw-complicat');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('0', 155, 2, 1213.29, 'Late vomit of preg-unsp');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('0695', 156, 3, 648.47, 'Compl kidney transplant');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('18568', 152, 4, 1472.19, 'Spinal cord disease NOS');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('89', 161, 3, 837.91, 'Sleep stage dysfunc NEC');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('8068', 150, 5, 357.1, 'Galactorrhea-nonobstet');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('376', 155, 2, 355.91, 'Brain neoplasm NOS');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('222', 154, 1, 957.86, 'Perinat jaund:hemolysis');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('5907', 149, 3, 184.94, 'Left heart failure');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('07156', 153, 2, 575.71, 'Ant disloc prox tibia-cl');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('472', 151, 2, 1381.4, 'Injury renal vein');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('3979', 162, 3, 1001.32, 'Mal neo liver, primary');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('52248', 159, 1, 1084.68, 'Yaws manifestations NEC');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('826', 147, 4, 1493.34, 'Anomalous av excitation');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('8', 153, 5, 521.63, 'Soft tissue disorder NEC');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('32', 153, 5, 664.19, 'Instantaneous death');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('0582', 158, 4, 641.11, 'Impair ren funct dis NEC');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('8668', 148, 1, 386.96, 'Undeterm circ-extrm cold');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('509', 161, 5, 632.67, 'Primary hyperparathyroid');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('7178', 153, 2, 1318.95, 'Obstruc labor NEC-antepa');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('47427', 154, 1, 691.58, 'Vag hi risk HPV-DNA pos');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('7965', 153, 3, 861.22, 'Ben neo lower jaw bone');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('99', 153, 1, 159.98, 'Benign neo epididymis');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('59', 147, 3, 213.23, 'Endometriosis NOS');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('9', 150, 4, 166.03, 'Primary atelectasis');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('57765', 162, 3, 1345.8, 'Milking an animal');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('287', 153, 2, 228.34, 'Synovial cyst NOS');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('9', 161, 2, 959.78, 'Sensory hear loss,unilat');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('3257', 149, 2, 736.76, 'Malig neopl bone NOS');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('0', 151, 2, 695.47, 'Intrinsic eustach obstr');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('38058', 160, 3, 910.41, 'Postlaminectomy kyphosis');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('23', 162, 4, 651.57, 'Other pulmonary insuff');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('4852', 148, 2, 1336.78, 'Angioneurotic edema');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('1786', 155, 4, 1442.81, 'Vertical heterophoria');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('8', 157, 5, 136.85, 'Bursitis NEC');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('32', 150, 2, 1060.51, 'Asym bacteriuria-deliver');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('42567', 158, 4, 1371.79, 'Pulmonary TB NOS-unspec');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('0', 157, 2, 411.58, 'Histoplasm capsul retina');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('7', 150, 4, 1253.35, 'Opn skul/oth fx-mod coma');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('93', 161, 1, 450.36, 'Radiat fetal damag-deliv');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('5', 161, 2, 1460.66, 'Opn skul fx NEC-mod coma');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('4822', 153, 4, 1273.83, 'Injury-caustic substance');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('964', 150, 2, 757.97, 'Unsat restore tooth NOS');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('792', 156, 4, 1198.65, 'Pneumoconiosis NOS');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('36', 153, 5, 1166.11, 'Gonococcal synovitis');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('01', 148, 2, 293.51, 'Inj musculocutan nerve');
insert into r_room (r_number, r_h_hotel, r_beds, r_price, r_description) values ('0906', 158, 4, 196.73, 'Subj visual disturb NOS');

insert into tr_typeOfRoom (tr_type) values ('King Bedroom');
insert into tr_typeOfRoom (tr_type) values ('Single Room');
insert into tr_typeOfRoom (tr_type) values ('Interconnecting Room');
insert into tr_typeOfRoom (tr_type) values ('Duplex');
insert into tr_typeOfRoom (tr_type) values ('Cabana');
insert into tr_typeOfRoom (tr_type) values ('Adjoining Room');
insert into tr_typeOfRoom (tr_type) values ('Hollywood Twin Room');
insert into tr_typeOfRoom (tr_type) values ('Double Room');
insert into tr_typeOfRoom (tr_type) values ('Double Double Room');
insert into tr_typeOfRoom (tr_type) values ('Twin Room');

delete from h_hotel
where h_hotelid = 155;

insert into re_reservation( re_r_room, re_checkIn, re_checkOut) values (8, '2017-08-19','2017-08-21');
insert into re_reservation( re_r_room, re_checkIn, re_checkOut) values (01, '2017-06-12','2017-06-13');