//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class re_reservation
    {
        public int re_reservationID { get; set; }
        public int re_r_room { get; set; }
        public System.DateTime re_checkIn { get; set; }
        public System.DateTime re_checkOut { get; set; }
    
        public virtual r_room r_room { get; set; }
    }
}
