//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class se_services
    {
        public string se_services1 { get; set; }
        public Nullable<int> se_h_hotelid { get; set; }
    
        public virtual h_hotel h_hotel { get; set; }
    }
}
