//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_user
    {
        public int u_username { get; set; }
        public string u_firstName { get; set; }
        public string u_lastName { get; set; }
        public string u_password { get; set; }
    }
}
